### PR TITLE
FormulaAndFunctionQueryDefinition group_by is list of objects, not dicts

### PR DESCRIPTION
**Pull request by ddadamhooper**
Fixes bugs uncovered by [DataDog/datadog-api-spec#5974](https://github.com/DataDog/datadog-api-spec/pull/5974) Test branch [datadog-api-spec/test/adam.hooper/topology-widget-freshen-2](https://github.com/DataDog/datadog-api-client-python/compare/datadog-api-spec/test/adam.hooper/topology-widget-freshen-2)

## Behavior change

Solved two small parsing bugs:

### `oneOf` matched both branches

Spotted during `TopologyMapWidgetDefinition` change.

After the schema change, `TopologyMapWidgetDefinitionDataStreams` has an attribute `requests` with each child a `TopologyRequestDataStreams`. And `TopologyMapWidgetDefinitionServiceMap` has an attribute `requests` with each child `TopologyRequestServiceMap`.

When parsing a service-map widget, we test both branches:

- `TopologyMapWidgetDefinitionServiceMap` => succeeds, because its `requests` contains a valid `TopologyRequestServiceMap`
- `TopologyMapWidgetDefinitionDataStreams` => **succeeds in error**, because its `requests` contains an _invalid_ `TopologyRequestDataStreams` but that `_unparsed` wasn't propagated to the _list_.

Fix: propagate `_unparsed` so the list is marked unparsed.

### Formula Events group-by lists failed to parse

Existing bug -- this is a breaking client-API change! It fixes another breaking client-API changed introduced in #3230.

#3230 (March 2026) introduced a regression: Formula Events group-by lists failed to parse.

What we wanted:

```python
query.get_oneof_instance()          # -> FormulaAndFunctionEventQueryDefinition
query._unparsed                     # -> False

gb = query.get_oneof_instance().group_by
type(gb)                            # -> list
gb[0].facet                         # -> '@geo.country_iso_code'
gb[0].sort.order.value              # -> 'desc'
```

What we shipped:

```python
query = <FormulaAndFunctionQueryDefinition>
query.get_oneof_instance()      # -> UnparsedObject   (not the real variant!)
query._unparsed                 # -> True             (but never surfaced)

gb = query.get_oneof_instance().group_by
type(gb)                        # -> list
gb                              # -> [{'facet': ..., 'limit': 250, 'sort': {...}}]  # raw dicts
gb[0].facet                     # -> AttributeError: 'dict' object has no attribute 'facet'
```

This is because the parser wouldn't accept `oneOf` where one branch is a list.

But **we didn't see this error** because we weren't propagating `_unparsed` correctly.

Fix: `deserialize_model()`: accept a list as a valid `oneOf` child.

## TL;DR

Customer-facing change in this PR:

- Parsing Dashboards API responses, formula group-by clauses WERE list-of-dicts, and are NOW list-of-objects. This fixes a regression.
- Parsing `AnyValue`: previously we'd return `UnparsedObject` for any value except for a `dict<str,str>`. Now we return `AnyValue`. This fixes a longstanding bug.

### CODE REVIEW

**Comment by ddadamhooper** [comment]
@codex review

File: src/datadog_api_client/model_utils.py [hunk 1]
```diff
@@ -84,7 +84,7 @@ def allows_single_value_input(cls):
     elif issubclass(cls, ModelComposed):
         if not cls._composed_schemas["oneOf"]:
             return False
-        return any(allows_single_value_input(c) for c in cls._composed_schemas["oneOf"] if not isinstance(c, list))
+        return any(isinstance(c, list) or allows_single_value_input(c) for c in cls._composed_schemas["oneOf"])
```
[the remark this answers is not in the document]
Comment (ddadamhooper) [reply src/datadog_api_client/model_utils.py:87]: Fixed in commit 4262243

**Review by jack-edmonds-dd — APPROVED** [review]

**Comment by ddadamhooper** [comment]
@codex review

File: src/datadog_api_client/model_utils.py [hunk 2]
```diff
@@ -1711,24 +1711,21 @@ def get_oneof_instance(cls, model_kwargs, constant_kwargs, model_arg=None):
...
-                        if list_oneof_instance:
+                        if constant_kwargs.get("_spec_property_naming"):
+                            list_oneof_instance = [
+                                oneof_class(**change_keys_js_to_python(arg, oneof_class), **constant_kwargs)
+                                for arg in model_arg
+                            ]
+                        else:
+                            list_oneof_instance = [oneof_class(**arg, **constant_kwargs) for arg in model_arg]
+                        # Reject the branch unless every element parsed.
+                        if list_oneof_instance and not any(item._unparsed for item in list_oneof_instance):
```
[the remark this answers is not in the document]
Comment (ddadamhooper) [reply src/datadog_api_client/model_utils.py]: commit 85501f8

**Comment by ddadamhooper** [comment]
@codex review

**Review by jack-edmonds-dd — APPROVED** [review]

File: src/datadog_api_client/model_utils.py [hunk 3]
```diff
@@ -1707,28 +1707,22 @@ def get_oneof_instance(cls, model_kwargs, constant_kwargs, model_arg=None):
...
-                                list_oneof_instance.append(oneof_instance)
-                        if list_oneof_instance:
+                        if constant_kwargs.get("_spec_property_naming"):
+                            list_oneof_instance = [
+                                oneof_class(**change_keys_js_to_python(arg, oneof_class), **constant_kwargs)
+                                for arg in model_arg
+                            ]
+                        else:
+                            list_oneof_instance = [oneof_class(**arg, **constant_kwargs) for arg in model_arg]
+                        if not any(item._unparsed for item in list_oneof_instance):
```
[the remark this answers is not in the document]
Comment (ddadamhooper) [reply src/datadog_api_client/model_utils.py]: commit 805bd2885

**Comment by ddadamhooper** [comment]
@codex review

File: src/datadog_api_client/model_utils.py [hunk 4]
```diff
@@ -1675,7 +1675,9 @@ def get_oneof_instance(cls, model_kwargs, constant_kwargs, model_arg=None):
         single_value_input = allows_single_value_input(oneof_class) if not isinstance(oneof_class, list) else True
 
         with suppress(Exception):
-            if not single_value_input:
+            if isinstance(model_class, list) and not isinstance(oneof_class, list):
```
[the remark this answers is not in the document]
Comment (ddadamhooper) [reply src/datadog_api_client/model_utils.py]: Typo! Fixed in commit 376d22332

**Comment by ddadamhooper** [comment]
@codex review

File: src/datadog_api_client/model_utils.py [hunk 5]
```diff
@@ -1707,28 +1710,22 @@ def get_oneof_instance(cls, model_kwargs, constant_kwargs, model_arg=None):
...
-                                )
-                            else:
-                                oneof_instance = oneof_class(**arg, **constant_kwargs)
-                            if not oneof_instance._unparsed:
-                                list_oneof_instance.append(oneof_instance)
-                        if list_oneof_instance:
+                        if constant_kwargs.get("_spec_property_naming"):
+                            list_oneof_instance = [
+                                oneof_class(**change_keys_js_to_python(arg, oneof_class), **constant_kwargs)
+                                for arg in model_arg
```
[the remark this answers is not in the document]
Comment (ddadamhooper) [reply src/datadog_api_client/model_utils.py]: In other words: `AnyValue` doesn't parse correctly. It didn't parse correctly before this PR, either. But I'll fix it anyway: commit befb3e5cc9f84769214d2e1404fc945a37d750db

**Comment by ddadamhooper** [comment]
@codex review

**Review by jack-edmonds-dd — APPROVED** [review]
