### ISSUE TITLE
Breaking change to metrics_query_metadata.py

### ISSUE THREAD

**Issue by michaelkimball** [DataDog/datadog-api-client-python#1501]
**Describe the bug**
There was a change to the client response for `MetricsApi(api_client).query_metrics` where the type for a pointlist was changed from `List[Point]` to `List[List[float]]` which breaks any existing script using the pointlist.

**To Reproduce**
have a script using the pointlist like
```python
from datetime import datetime
from datadog_api_client import ApiClient, Configuration
from datadog_api_client.v1.api.metrics_api import MetricsApi

import argparse
import json

argParser = argparse.ArgumentParser()
argParser.add_argument("-d", "--date", help="Date")
args = argParser.parse_args()

startdate = args.date + 'T00:00:00-05:00'
enddate = args.date + 'T20:00:00-05:00'

configuration = Configuration()

def get_point_total(response):
    total = 0.0
    pointlist = response.series[0].get('pointlist', None)
    for x in pointlist:
        total += x.value[1]
    return total

def query_metric(query_string):
    with ApiClient(configuration) as api_client:
        api_instance = MetricsApi(api_client)
        response = api_instance.query_metrics(
            _from=int((datetime.fromisoformat(startdate).timestamp())),
            to=int(datetime.fromisoformat(enddate).timestamp()),
            query=query_string,
        )
        return response

request_count_response = query_metric("sum:aws.applicationelb.request_count{*}.as_count()")
request_count = get_point_total(request_count_response)

json_summary = {
    "blocks": [
        {
	    "type": "header",
	    "text": {
	        "type": "plain_text",
	        "text": "Day end summary for {}".format(args.date)
            }
	},
        {
	    "type": "section",
            "fields": [
                {
	            "type": "mrkdwn",
	            "text": "*App Requests:*\n{}".format(round(request_count))
                }
            ]
	},
    ]
}

print(json.dumps(json.dumps(json_summary)))
```
where you call it with
```sh
python get_dd_metrics.py --date 2023-06-02
```

**Expected behavior**
I would expect an output of
```sh
"{\"blocks\": [{\"type\": \"header\", \"text\": {\"type\": \"plain_text\", \"text\": \"Day end summary for 2023-06-02\"}}, {\"type\": \"section\", \"fields\": [{\"type\": \"mrkdwn\", \"text\": \"*App Requests:*\\n1403599\"}]}]}"
```

**Actual behavior**
```sh
Traceback (most recent call last):
  File "/home/myuser/dd-scripts/test.py", line 35, in <module>
    request_count = get_point_total(request_count_response)
  File "/home/myuser/dd-scripts/test.py", line 21, in get_point_total
    total += x.value[1]
AttributeError: 'list' object has no attribute 'value'
```

**Proposed Resolution**
Seeing as this is a **breaking** change, and I believe you all follow [semver standards](https://semver.org/#if-even-the-tiniest-backward-incompatible-changes-to-the-public-api-require-a-major-version-bump-wont-i-end-up-at-version-4200-very-rapidly) I would expect there to be a bump in the **major** version of your release tag. If you introduce backwards incompatible changes then you should bump the major version to indicate that there is a break so that users are not caught unaware along with a comparison of the old usage and the new usage.

**Environment and Versions (please complete the following information):**
A clear and precise description of your setup:
You can reproduce this with:
- `Python 3.10.11`
- `datadog-api-client 2.13.1`
- `argparse 1.4.0`
- `Ubuntu 20.04.5 LTS (Focal Fossa)`

**Additional Context**
This change seems to have been introduced in #1431 and you can find the specific change [here](https://github.com/DataDog/datadog-api-client-python/pull/1431/files#diff-e0a7650f90f0935510e0682c0d84b79ccf0ea9735805d31a71aba10e95a7b4ddL91-R89)

**Comment by michaelkimball** [comment]
I'm not able to add labels, but I would label it with severity/major

**Comment by michaelkimball** [comment]
Thanks for the quick response @therve! Yes, I think that is a perfect solution. Also, if you can add to the new release what the breaking change is that would be appreciated.
